name: snackish
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/
    - assets/grafiken/
    - assets/details/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400


